# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# new cred
#sas added
trigger:
- main

pool:
  vmImage: ubuntu-latest
jobs:
- job: job1
  steps:
    - script: echo Hello, world!--updated
      displayName: 'Run a one-line script'
          
    
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes/'
        commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFile)'
        backendServiceArm: 'test-azure-service-connection'
        backendAzureRmResourceGroupName: 'user127_1_rg'
        backendAzureRmStorageAccountName: 'armaccyeqfjho233kdq'
        backendAzureRmContainerName: 'testcontainer'
        backendAzureRmKey: 'kubdef.tfstate'
      env:
        ARM_SAS_TOKEN: 'sp=racwl&st=2026-07-10T15:50:36Z&se=2026-07-11T00:05:36Z&sv=2026-02-06&sr=c&sig=IBkOHtmZaJhoXNZMOOwGycn1e1ZO9cqd3s957tonM9Y%3D'  
